Frontweb/Frontweb/Models/ErrorViewModel.cs
namespace Frontweb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Frontweb/Frontweb/Models/Tb_PersonasFisicas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Frontweb.Models
{
    public class Tb_PersonasFisicas
    {
        [Key]
        public int IdPersonaFisica { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public DateTime? FechaActualizacion { get; set; }

        public string? Nombre { get; set; }
        public string? ApellidoPaterno { get; set; }
        public string? ApellidoMaterno { get; set; }
        public string? RFC { get; set; }

        public DateTime? FechaNacimiento { get; set; }
        public int? UsuarioAgrega { get; set; }
        public bool? Activo { get; set; }
    }
}

Frontweb/Frontweb/Controllers/HomeController.cs
using Frontweb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Frontweb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Frontweb/Frontweb/Controllers/Tb_PersonasFisicasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Frontweb.Models;
using Newtonsoft.Json;
using System;
using System.Text;

namespace Frontweb.Controllers
{
    public class Tb_PersonasFisicasController : Controller
    {
        HttpClientHandler handler = new HttpClientHandler();

        Tb_PersonasFisicas personasFisica = new Tb_PersonasFisicas();
        List<Tb_PersonasFisicas> personasFisicas = new List<Tb_PersonasFisicas>();


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Reports()
        {
            return View();
        }


        public Tb_PersonasFisicasController()
        {
            handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) =>
            {
                return true;
            };
        }

        [HttpGet]
        public async Task<List<Tb_PersonasFisicas>> GetPersons()
        {
            personasFisicas = new List<Tb_PersonasFisicas>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7263/api/Tb_PersonasFisicas"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    personasFisicas = JsonConvert.DeserializeObject<List<Tb_PersonasFisicas>>(apiResponse);

                }
            }

            return personasFisicas;
        }

        [HttpGet]
        public async Task<Tb_PersonasFisicas> GetByID(int IdPersonaFisica)
        {
            personasFisica = new Tb_PersonasFisicas();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7263/api/Tb_PersonasFisicas/" + IdPersonaFisica))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    personasFisica = JsonConvert.DeserializeObject<Tb_PersonasFisicas>(apiResponse);
                }
            }

            return personasFisica;
        }

        [HttpPost]
        public async Task<Tb_PersonasFisicas> insert(Tb_PersonasFisicas _personasFisica)
        {
            personasFisica = new Tb_PersonasFisicas();

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(
                    JsonConvert.SerializeObject(_personasFisica), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7263/api/Tb_PersonasFisicas", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    personasFisica = JsonConvert.DeserializeObject<Tb_PersonasFisicas>(apiResponse);
                }
            }

            return personasFisica;
        }

        [HttpPut]
        public async Task<Tb_PersonasFisicas> Update(int IdPersonaFisica, Tb_PersonasFisicas _personasFisica)
        {
            personasFisica = new Tb_PersonasFisicas();

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(
                    JsonConvert.SerializeObject(_personasFisica), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync("https://localhost:7263/api/Tb_PersonasFisicas/" + IdPersonaFisica, content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    personasFisica = JsonConvert.DeserializeObject<Tb_PersonasFisicas>(apiResponse);
                }
            }

            return personasFisica;
        }


        [HttpDelete]
        public async Task<string> Delete(int IdPersonaFisica)
        {
            string message = "";

            using (var httpClient = new HttpClient(handler))
            {
                using (var response = await httpClient.DeleteAsync("https://localhost:7263/api/Tb_PersonasFisicas/" + IdPersonaFisica))
                {
                    message = await response.Content.ReadAsStringAsync();
                }
            }

            return message;
        }

    }
}

Frontweb/Frontweb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Frontweb/Frontweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Front web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Frontweb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >Frontweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tb_PersonasFisicas" asp-action="Index"> Modulo de Personas Fisicas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tb_PersonasFisicas" asp-action="Reports">Reportes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.js"></script>
    <script  type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.2.0/js/tableexport.min.js" integrity="sha512-XmZS54be9JGMZjf+zk61JZaLZyjTRgs41JLSmx5QlIP5F+sSGIyzD2eJyxD4K6kGGr7AsVhaitzZ2WTfzpsQzg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Frontweb/Frontweb/Views/Tb_PersonasFisicas/Index.cshtml
@{
    ViewData["Title"] = "Persona Fisica";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/lib/jquery/dist/jquery.min.js" ></script>

<h2> Añadir Persona </h2>

<div class="form-group" style="display: none;">
    <input id="IdPersonaFisica" class="form-control" name="IdPersonaFisica"/>
</div>
<div class="form-group">
    <label for="Nombre" >Nombre: </label>
    <input id="Nombre" class="form-control" name="Nombre" />
</div>
<div class="form-group">
    <label for="ApellidoPaterno" >Apellido Paterno: </label>
    <input id="ApellidoPaterno" class="form-control" name="ApellidoPaterno" />
</div>
<div class="form-group">
    <label for="ApellidoMaterno" >Apellido Materno: </label>
    <input id="ApellidoMaterno" class="form-control" name="ApellidoMaterno" />
</div>
<div class="form-group">
    <label for="RFC" >RFC: </label>
    <input id="RFC" class="form-control" name="RFC" />
</div>
<div class="form-group">
    <label for="FechaNacimiento" >Fecha de Nacimiento: </label>
    <input id="FechaNacimiento" type="date" class="form-control" name="FechaNacimiento" />
</div>
<div class="form-group">
    <label for="UsuarioAgrega" >Identificador de administrador: </label>
    <input id="UsuarioAgrega" class="form-control" name="UsuarioAgrega" />
</div>

<div class="text-center panel-body" style="margin-top: 10px">
    <button id="btnSave"  onclick="Insert()" class="btn btn-md btn-success">Guardar</button>
</div>

<div class="container" style="margin-top:50px">
    <div class="row">
        <div class="col-10">
        <h2>Registros añadidos</h2>
        </div>

        <div class="col-2">
        <button onclick="getRecords()" class="btn btn-primary">Cargar registros</button>
        </div>
    </div>
</div>

<div style="margin-top:30px">
    <table id="tblPersonasFisicas" class="table table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido Paterno</th>
                <th>Apellido Materno</th>
                <th>RFC</th>
                <th>Fecha de Nacimiento</th>
                <th>Estado</th>
                <th>Fecha de Registro</th>
                <th>Fecha de Actualizacion</th>
                <th>Accion</th>
            </tr>
        </thead>
    </table>
</div>


<script type="text/javascript">

    let flagEdit = false;

    const getRecords = () => {
        $.getJSON("/Tb_PersonasFisicas/GetPersons",(persons) => {
            $("#tblPersonasFisicas td").remove(); 
            persons.map((person,index) => {
                $("#tblPersonasFisicas").append("<tr>" 
                    + "<td>" + person.idPersonaFisica + "</td>"
                    + "<td>" + person.nombre + "</td>"
                    + "<td>" + person.apellidoPaterno + "</td>"
                    + "<td>" + person.apellidoMaterno + "</td>"
                    + "<td>" + person.rfc + "</td>"
                    + "<td>" + person.fechaNacimiento + "</td>"
                    + "<td>" + person.activo + "</td>"
                    + "<td>" + person.fechaRegistro + "</td>"
                    + "<td>" + person.fechaActualizacion + "</td>"
                    + "<td>"
                    +   "<button class='btn-success' onclick='Edit("+person.idPersonaFisica+")'>Editar</button>"
                    +   "<button class='btn-danger' onclick='Delete("+person.idPersonaFisica+")'>Eliminar</button>"
                    + "</td>"
                    + "</tr>"
                );
            })
        });
    }

    const Edit = (IdPersonaFisica) => {
        if(IdPersonaFisica > 0){
            $.getJSON("/Tb_PersonasFisicas/GetByID?IdPersonaFisica="+IdPersonaFisica,(persons) => {
                $("#IdPersonaFisica").val(persons.idPersonaFisica);
                $("#Nombre").val(persons.nombre);
                $("#ApellidoPaterno").val(persons.apellidoPaterno);
                $("#ApellidoMaterno").val(persons.apellidoMaterno);
                $("#RFC").val(persons.rfc);
                $("#FechaNacimiento").val(persons.fechaNacimiento);
                $("#UsuarioAgrega").val(persons.usuarioAgrega);
            });
            flagEdit = true
        }
    }

    const Delete = (IdPersonaFisica) => {
        if(IdPersonaFisica > 0){
            $.ajax({
                url: '/Tb_PersonasFisicas/Delete?IdPersonaFisica=' + IdPersonaFisica,
                type: 'DELETE',
                dataType: 'json',
                success: (data) => {
                },
                error: (ex) => {
                    console.log("error", ex)
                }
            })            
        }
    }

    const Insert = () => {

        if ($('#Nombre').val() != ''){
            let personasFisica = {
                nombre: $("#Nombre").val(),
                apellidoPaterno: $("#ApellidoPaterno").val(),
                apellidoMaterno: $("#ApellidoMaterno").val(),
                rfc: $("#RFC").val(),
                fechaNacimiento: $("#FechaNacimiento").val(),
                usuarioAgrega: $("#UsuarioAgrega").val(),
                activo: true,
                fechaRegistro: new Date().toISOString().split('T')[0],
                fechaActualizacion: new Date().toISOString().split('T')[0]
            }

            if(flagEdit){
                $.ajax({
                    url: "/Tb_PersonasFisicas/Update?IdPersonaFisica="+ $("#IdPersonaFisica").val(),
                    type: 'PUT',
                    dataType: 'json',
                    data: personasFisica,
                    success: (data) => {
                        flagEdit = false,           
                        getRecords
                    },
                    error: (ex) => {
                        console.log("error", ex)
                    }
                })             
            }
            else{
                $.post("/Tb_PersonasFisicas/insert",personasFisica).done((data) => {
                    getRecords
                })
            }
            $("#IdPersonaFisica").val('');
            $("#Nombre").val('');
            $("#ApellidoPaterno").val('');
            $("#ApellidoMaterno").val('');
            $("#RFC").val('');
            $("#FechaNacimiento").val('');
            $("#UsuarioAgrega").val(''); 
        }
    }
    
</script>

Frontweb/Frontweb/Views/Tb_PersonasFisicas/Reports.cshtml
@{
    ViewData["Title"] = "Reportes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.min.js" ></script>


<div>
    <h2 style="text-align: center"> Reportes </h2>

    <table id="example" class="display" style="width:100%; margin-top: 90px">
        <thead>
            <tr>
                <th>Id Cliente</th>
                <th>Fecha de Registro en la Empresa</th>
                <th>Razon Social</th>
                <th>RFC</th>
                <th>Sucursal</th>
                <th>Id Empleado</th>
                <th>Nombre</th>
                <th>Paterno</th>
                <th>Materno</th>
                <th>Id Viaje</th>
            </tr>
        </thead>
    </table>

    <button class="btn btn-primary" id="btnExport" onclick="ExportToExcel('xlsx')">Exportar como csv</button>
</div>


<script type="text/javascript">

    window.onload = function () {
        getToken()
    }


    const getToken = () => {
        $.ajax({
            url : 'https://api.toka.com.mx/candidato/api/login/authenticate',
            type: 'POST',
            data : {
                Username: "ucand0021",
                Password: "yNDVARG80sr@dDPc2yCT!" 
            },
            dataType : 'json',            
            success: (data) => {
                setTable(data.Data)     
            },
            error: (ex) => {
                console.log("error", ex)
            }
        })   
    }

    const setTable = (token) => {
        $.ajax({
            url : 'https://api.toka.com.mx/candidato/api/customers',
            data : {},
            type: 'GET',
            dataType : 'json',
            headers: {'Authorization': `Bearer ${token} `},
            
            success: (data) => {
                let t = $('#example').DataTable();
                data.Data.forEach(element => {
                    t.row.add([
                        element.IdCliente,
                        element.FechaRegistroEmpresa,
                        element.RazonSocial,
                        element.RFC,
                        element.Sucursal,
                        element.IdEmpleado,
                        element.Nombre,
                        element.Paterno,
                        element.Materno,
                        element.IdViaje
                    ] ).draw( false );
                })
            },
            error: (ex) => {
                console.log("error", ex)
            }
        })
    }

    $(document).ready(function() {
        $('#example').DataTable( {
            "pagingType": "full_numbers"
        } );
    });

    const  ExportToExcel = (type, fn, dl) => {
       let elt = document.getElementById('example');
       let wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });
       return dl ?  XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }): XLSX.writeFile(wb, fn || ('TokaData.' + (type || 'xlsx')));
    }


</script>